### ISSUE TITLE
¿en dónde montamos los podcasts?

### ISSUE THREAD

**Issue by juanpabloe** [rogeliog/podcrafts#2]
Tenemos que montar un pequeño site qué después abra un RSS feed para suscribirlo a iTunes Store.
Lo más fácil sería usar Soundcloud como servicio y de ahí suscribirlo al iTunes Store. Después montar un static site que indexe todos los episodios.

Cómo ves? @rogeliog

**Comment by rogeliog** [comment]
Si, yo creo que subirlos a Soundcloud es buena idea. Tener un site estaría a super bien pero creo que nos podemos empezar a preocupar de eso después. Yo creo que subirlo a Soundcloud y publicarlo a ITunes, etc, sería un mas que excelente comienzo :)

https://on.soundcloud.com/creator-guide/podcasting

Tu que opinas @rodowi?

**Comment by rogeliog** [comment]
https://soundcloud.com/podcrafts
https://twitter.com/podcrafts

**Comment by defvol** [comment]
soundcloud, fácil

primero grabemos y después veamos el front page
