### ISSUE TITLE
Posibles fechas para empezar

### ISSUE THREAD

**Issue by rogeliog** [rogeliog/podcrafts#3]
Cuando creen que sea una buena fecha para grabar el primero?

Creo que para el primero no necesitamos mucha preparación, el primero puede ser extra informal y básicamente hablar de que va a hacer el podcast, rebotar ideas, ver como se siente, y todo eso.

Yo estaba pensando algo como martes, miércoles o jueves, entre la hora que se nos acomode entre 10am y 2pm(PDT) o a que hora se les acomoda a ustedes?

**Comment by juanpabloe** [comment]
Yo prefiero sea en las noches entre 8 pm y 10 pm CDT (6 y 8 PDT). Pero puedo ver la forma de ajustarme si a ustedes no les funciona.
edit: estaría muy bueno sea esta semana el jueves

**Comment by rogeliog** [comment]
Oigan como andan esta semana tipo el miercoles o el jueves?

**Comment by defvol** [comment]
los martes se me hace mejor día, pero en general cualquiera de esos 3 días entre 8 y 10pm EDT.

**Comment by juanpabloe** [comment]
El martes suena muy buen día.

Excepto este que estaré en un vuelo. Empezamos próximo miércoles y luego
switcheamos a martes? :D

**Comment by defvol** [comment]
no puedo este miércoles

**Comment by rogeliog** [comment]
Yo puedo el día que sea

**Comment by juanpabloe** [comment]
Este Jueves si o si Podcrafters?

**Comment by defvol** [comment]
Este jueves! 🚀

**Comment by rogeliog** [comment]
🎉🎉🎉
